
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace el_shabander
{

using System;
    using System.Collections.Generic;
    
public partial class AppSetting
{

    public int id { get; set; }

    public string namecomp { get; set; }

    public string address { get; set; }

    public string phonenam { get; set; }

    public byte[] logocomp { get; set; }

    public string printty { get; set; }

    public Nullable<int> max_qt { get; set; }

    public string printcod { get; set; }

    public string description { get; set; }

}

}
