//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el_shabander
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_storeEntities : DbContext
    {
        public DB_storeEntities()
            : base("name=DB_storeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<Notfication> Notfications { get; set; }
        public virtual DbSet<TB_cat> TB_cat { get; set; }
        public virtual DbSet<tb_cus> tb_cus { get; set; }
        public virtual DbSet<tb_employees> tb_employees { get; set; }
        public virtual DbSet<tb_factory> tb_factory { get; set; }
        public virtual DbSet<tb_ordersell> tb_ordersell { get; set; }
        public virtual DbSet<tb_ordersellpop> tb_ordersellpop { get; set; }
        public virtual DbSet<tb_pur> tb_pur { get; set; }
        public virtual DbSet<tb_rev_cus> tb_rev_cus { get; set; }
        public virtual DbSet<tb_rev_supp> tb_rev_supp { get; set; }
        public virtual DbSet<tb_safe> tb_safe { get; set; }
        public virtual DbSet<tb_sell> tb_sell { get; set; }
        public virtual DbSet<tb_sellpop> tb_sellpop { get; set; }
        public virtual DbSet<tb_spend_cus> tb_spend_cus { get; set; }
        public virtual DbSet<tb_spend_supp> tb_spend_supp { get; set; }
        public virtual DbSet<tb_stor> tb_stor { get; set; }
        public virtual DbSet<tb_stuk> tb_stuk { get; set; }
        public virtual DbSet<tb_supp> tb_supp { get; set; }
        public virtual DbSet<tb_takestuk> tb_takestuk { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
        public virtual DbSet<tb_add_mony> tb_add_mony { get; set; }
        public virtual DbSet<tb_offer> tb_offer { get; set; }
        public virtual DbSet<sendmailcode> sendmailcodes { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<tb_OperationLog> tb_OperationLog { get; set; }
    }
}
