//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el_shabander
{
    using System;
    using System.Collections.Generic;
    
    public partial class sendmailcode
    {
        public int id { get; set; }
        public string user_mail { get; set; }
        public string code { get; set; }
    }
}
