
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace el_shabander
{

using System;
    using System.Collections.Generic;
    
public partial class Session
{

    public int SessionID { get; set; }

    public Nullable<System.DateTime> StartTime { get; set; }

    public Nullable<System.DateTime> EndTime { get; set; }

    public Nullable<bool> IsClosed { get; set; }

    public Nullable<double> OpeningAmount { get; set; }

    public string namecasher { get; set; }

    public Nullable<double> ClosingAmount { get; set; }

}

}
