
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace el_shabander
{

using System;
    using System.Collections.Generic;
    
public partial class tb_add_mony
{

    public int id { get; set; }

    public string name_type { get; set; }

    public Nullable<double> price { get; set; }

    public Nullable<System.DateTime> date { get; set; }

    public string typemotion { get; set; }

}

}
