
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace el_shabander
{

using System;
    using System.Collections.Generic;
    
public partial class tb_cus
{

    public int id { get; set; }

    public string cus_name { get; set; }

    public string cus_phone { get; set; }

    public string cus_email { get; set; }

    public byte[] cus_image { get; set; }

    public Nullable<double> total_price { get; set; }

    public Nullable<double> cus_max { get; set; }

}

}
