
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace el_shabander
{

using System;
    using System.Collections.Generic;
    
public partial class tb_employees
{

    public int id { get; set; }

    public string emp_name { get; set; }

    public string emp_type_emp { get; set; }

    public string emp_freeday { get; set; }

    public string emp_datemont { get; set; }

    public string emp_dat { get; set; }

    public Nullable<double> emp_salers { get; set; }

    public Nullable<double> emp_paysalers { get; set; }

    public Nullable<double> emp_staysalers { get; set; }

    public byte[] emp_image { get; set; }

    public Nullable<double> emp_absent { get; set; }

}

}
