
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace el_shabander
{

using System;
    using System.Collections.Generic;
    
public partial class tb_factory
{

    public int id { get; set; }

    public string cat_name { get; set; }

    public string cat_name_fact { get; set; }

    public Nullable<System.DateTime> date { get; set; }

    public Nullable<double> qt { get; set; }

    public Nullable<double> cost_all { get; set; }

    public string unit { get; set; }

}

}
