//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el_shabander
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OperationLog
    {
        public int LogID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string OperationType { get; set; }
        public string TableName { get; set; }
        public Nullable<double> OldValue { get; set; }
        public Nullable<double> NewValue { get; set; }
        public Nullable<double> AmountDifference { get; set; }
    }
}
