//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el_shabander
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ordersellpop
    {
        public int id { get; set; }
        public string name_sell { get; set; }
        public Nullable<double> price_sell { get; set; }
        public Nullable<double> qt_sell { get; set; }
        public Nullable<double> tprice_sell { get; set; }
        public Nullable<int> sell_id { get; set; }
        public string wight { get; set; }
        public Nullable<double> sell_price_sell { get; set; }
        public Nullable<double> karat { get; set; }
    }
}
