
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace el_shabander
{

using System;
    using System.Collections.Generic;
    
public partial class tb_offer
{

    public int id { get; set; }

    public string name_offer { get; set; }

    public string type_offer { get; set; }

    public Nullable<double> quontity { get; set; }

}

}
