//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el_shabander
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pur
    {
        public int id { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> supp_id { get; set; }
        public string pur_name { get; set; }
        public string pur_type { get; set; }
        public string pur_cat { get; set; }
        public string pur_supp { get; set; }
        public Nullable<double> pur_buy { get; set; }
        public Nullable<double> pay { get; set; }
        public Nullable<double> pur_qt { get; set; }
        public Nullable<double> stay { get; set; }
        public Nullable<double> pur_tbuy { get; set; }
        public Nullable<double> pur_trev { get; set; }
        public Nullable<System.DateTime> pur_dat { get; set; }
        public string safe { get; set; }
        public Nullable<double> supp_price { get; set; }
        public Nullable<double> total_price { get; set; }
        public Nullable<int> invocie_id { get; set; }
        public string namecasher { get; set; }
    }
}
