
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace el_shabander
{

using System;
    using System.Collections.Generic;
    
public partial class tb_sell
{

    public int id { get; set; }

    public string sell_name { get; set; }

    public string sell_cus { get; set; }

    public Nullable<double> sell_price { get; set; }

    public Nullable<double> sell_qt { get; set; }

    public Nullable<double> sell_tprice { get; set; }

    public Nullable<System.DateTime> sell_date { get; set; }

    public Nullable<double> pay { get; set; }

    public Nullable<double> stay { get; set; }

    public Nullable<double> total_price { get; set; }

    public Nullable<int> cus_id { get; set; }

    public Nullable<double> total_sell { get; set; }

    public string safe { get; set; }

    public Nullable<double> cut { get; set; }

    public Nullable<double> sell_add { get; set; }

    public Nullable<double> cus_price { get; set; }

    public Nullable<int> invocie_id { get; set; }

    public Nullable<double> total_earnings { get; set; }

    public string name_cascher { get; set; }

}

}
