//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el_shabander
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_stor
    {
        public int id { get; set; }
        public string stor_det { get; set; }
        public Nullable<double> stor_spen { get; set; }
        public string stor_type { get; set; }
        public Nullable<System.DateTime> stor_dete { get; set; }
        public string stor_empname { get; set; }
        public string safe_name { get; set; }
        public string namecasher { get; set; }
    }
}
