//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el_shabander
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_supp
    {
        public int id { get; set; }
        public string supp_name { get; set; }
        public string supp_phone { get; set; }
        public string supp_email { get; set; }
        public byte[] supp_image { get; set; }
        public Nullable<double> total_price { get; set; }
        public Nullable<double> supp_max { get; set; }
    }
}
