//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el_shabander
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_spend_cus
    {
        public int id { get; set; }
        public string name_cus { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> mony_spend { get; set; }
        public Nullable<double> mony_rev { get; set; }
        public Nullable<double> mony_stay { get; set; }
        public string safe { get; set; }
        public string namecasher { get; set; }
    }
}
