//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el_shabander
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_stuk
    {
        public int id { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> supp_id { get; set; }
        public Nullable<double> stuk_buy { get; set; }
        public Nullable<double> stuk_qt { get; set; }
        public string stuk_name { get; set; }
        public string stuk_type { get; set; }
        public string stuk_cat { get; set; }
        public string stuk_supp { get; set; }
        public byte[] barcode_img { get; set; }
        public Nullable<double> stuk_tsell { get; set; }
        public Nullable<double> stuk_sell { get; set; }
        public Nullable<double> stuk_qtfact { get; set; }
        public Nullable<double> stuk_costfsctory { get; set; }
        public Nullable<double> stuk_qtfacttotal { get; set; }
        public string unit { get; set; }
        public string code { get; set; }
        public string type_fact { get; set; }
        public Nullable<int> karat { get; set; }
        public Nullable<double> weight_g { get; set; }
        public Nullable<double> making_charge { get; set; }
        public string price_mode { get; set; }
    }
}
