
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace el_shabander
{

using System;
    using System.Collections.Generic;
    
public partial class tb_takestuk
{

    public int id { get; set; }

    public string stuk_takename { get; set; }

    public Nullable<double> stuk_takeqt { get; set; }

    public Nullable<double> stuk_takesell { get; set; }

    public Nullable<int> stuk_id { get; set; }

    public Nullable<double> stuk_takeqtstay { get; set; }

    public Nullable<double> stuk_takeqttotal { get; set; }

}

}
