//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace el_shabander
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string user_pass { get; set; }
        public string user_roll { get; set; }
        public string user_state { get; set; }
        public byte[] user_image { get; set; }
        public string user_mail { get; set; }
    }
}
