using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using el_shabander.epl;
namespace el_shabander.pl
{
    public partial class frm_cat : Form
    {
        DB_storeEntities db = new DB_storeEntities();
        TB_cat tB_Cat = new TB_cat();
        bl.methods methods = new bl.methods();
        //toast toast = new toast();
        
        int id;
        public frm_cat()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            el_shabander.DB_storeEntities dbContext = new el_shabander.DB_storeEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.tb_stuk.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.tb_stuk.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            pl.frm_cat_add frm_Cat_Add = new frm_cat_add();
            frm_Cat_Add.id = 0;
            frm_Cat_Add.btn_add.Text = "اضافة";
            frm_Cat_Add.Show();
        }

        private void btn_updata_Click(object sender, EventArgs e)
        {
            updata_data();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {

            toast toast = new toast();
            dialog dialog = new dialog();
            try
            {
                id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("id"));
                var tb_stuk = db.tb_stuk.FirstOrDefault(x => x.id == id);

                if (tb_stuk == null)
                {
                    dialog.Width = this.Width;
                    dialog.txt_capthion.Text = "الصنف غير موجود.";
                    dialog.Show();
                    return;
                }

                // التحقق إذا كانت الكمية أكبر من صفر
                if (tb_stuk.stuk_qt > 0)
                {
                    MessageBox.Show("لا يمكن حذف هذا الصنف لأنه يحتوي على كمية في المخزن.", "تنبيه", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    return;
                }

                var rs = MessageBox.Show("عملية حذف", "هل انت متأكد من هذه العملية؟", MessageBoxButtons.YesNo);
                if (rs == DialogResult.Yes)
                {
                    db.Entry(tb_stuk).State = EntityState.Deleted;
                    db.SaveChanges();

                    toast.txt_caption.Text = "تم الحذف بنجاح";
                    toast.Show();
                    updata_data();
                }
            }
            catch
            {
                dialog.Width = this.Width;
                dialog.txt_capthion.Text = "لا يوجد صنف لحذفه";
                dialog.Show();
            }
        }

        public void updata_data()
        {
            db = new DB_storeEntities();
            gridControl1.DataSource = db.tb_stuk.ToList();
        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            pl.frm_stuck_add frm_Cat_Add = new frm_stuck_add();
            id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("id"));
            var tb_stuk = db.tb_stuk.Where(x => x.id == id).FirstOrDefault();
            frm_Cat_Add.edt_name.Text = tb_stuk.stuk_name;
            frm_Cat_Add.edt_name_old.Text = tb_stuk.stuk_name;
            frm_Cat_Add.edt_code.Text = tb_stuk.code;
            frm_Cat_Add.edt_cat.DataSource = db.TB_cat.Select(x => x.cat_name).ToList();
            frm_Cat_Add.edt_cat.Text=tb_stuk.stuk_cat;
            frm_Cat_Add.unit_small.Text = tb_stuk.stuk_type;
            frm_Cat_Add.unit_big.Text = tb_stuk.stuk_supp;
            frm_Cat_Add.edt_type.Text = tb_stuk.type_fact;
            frm_Cat_Add.edt_big.Text= tb_stuk.stuk_qtfacttotal.ToString();
            frm_Cat_Add.id = id;
            frm_Cat_Add.btn_add.Text = "تعديل";
            frm_Cat_Add.Show();
        }
       

            private void btn_search_Click(object sender, EventArgs e)
        {
            var _search = edit_txt.Text;
            gridControl1.DataSource = db.tb_stuk.Where(x => x.stuk_name.Contains(_search)).ToList();
        }

        private void btn_add_prod_Click(object sender, EventArgs e)
        {
            pl.frm_stuck_add frm_Cat_Add = new frm_stuck_add();
            frm_Cat_Add.id = 0;
           
            frm_Cat_Add.Show();
        }

        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {
            btn_edit_Click(sender, e);
        }
    }
}
