using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using el_shabander.epl;
namespace el_shabander.pl
{
    public partial class frm_factory : Form
    {
        DB_storeEntities db = new DB_storeEntities();
        tb_pur tb_Pur = new tb_pur();
        bl.methods methods = new bl.methods();
        toast toast = new toast();
        tb_safe tb_Safe = new tb_safe();
        tb_stuk tb_stuk = new tb_stuk();
        tb_supp tb_Supp = new tb_supp();

        int id;
        public frm_factory()
        {
            InitializeComponent();


           
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            el_shabander.DB_storeEntities dbContext = new el_shabander.DB_storeEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.tb_factory.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.tb_factory.Local.ToBindingList().Reverse();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            gridView1.OptionsBehavior.Editable = false;
        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            pl.frm_factory_add frm_supp_Add = new frm_factory_add();
            frm_supp_Add.id = 0;
            
            frm_supp_Add.Show();
        }

        private void btn_updata_Click(object sender, EventArgs e)
        {
            updata_data();
        }
        public List<tb_ordersellpop> listorder;
        private void btn_delete_Click(object sender, EventArgs e)
        {
            toast toast = new toast();
            dialog dialog = new dialog();
            try
            {
                id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("id"));
                var rs = MessageBox.Show("عملية حذف", "هل انت متاكد من هذة العملية", MessageBoxButtons.YesNo);
                if (rs == DialogResult.Yes)
                {
                    // استرجاع البيانات من tb_factory
                    var tb_factory = db.tb_factory.FirstOrDefault(x => x.id == id);
                    if (tb_factory != null)
                    {
                        double oldQuantity = Convert.ToDouble(tb_factory.qt);
                        bool oldUnitIsSmall = tb_factory.unit == "صغرى";
                        
                        // العثور على المنتج الأول لإرجاع الكمية القديمة
                        var tb_stuk = db.tb_stuk.FirstOrDefault(x => x.stuk_name == tb_factory.cat_name);
                        var tb_stuk2 = db.tb_stuk.FirstOrDefault(x => x.stuk_name == tb_factory.cat_name_fact);
                       

                        if (tb_stuk != null)
                        {
                            if (oldUnitIsSmall) // في حالة الوحدة القديمة كانت "صغرى"
                            {
                                if (tb_stuk2.stuk_qt < oldQuantity)
                                {
                                    MessageBox.Show("لا يمكن حذف هذه العملية لأن الكمية في المخزن أقل من الكمية المطلوبة.", "تحذير", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                    return; // إنهاء العملية هنا إذا لم تكن الكمية كافية
                                }
                                tb_stuk.stuk_qt += oldQuantity;
                            }
                            else // في حالة الوحدة القديمة كانت "كبرى"
                            {
                                if (tb_stuk2.stuk_qt < oldQuantity * tb_stuk.stuk_qtfacttotal)
                                {
                                    MessageBox.Show("لا يمكن حذف هذه العملية لأن الكمية في المخزن أقل من الكمية المطلوبة.", "تحذير", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                    return; // إنهاء العملية هنا إذا لم تكن الكمية كافية
                                }
                                tb_stuk.stuk_qt += oldQuantity * tb_stuk.stuk_qtfacttotal;
                            }
                            db.Entry(tb_stuk).State = EntityState.Modified;
                            db.SaveChanges();
                        }

                        // العثور على المنتج الثاني لحذف الكمية القديمة من tb_stuk2
                       
                        if (tb_stuk2 != null)
                        {
                            if (oldUnitIsSmall) // في حالة الوحدة القديمة كانت "صغرى"
                            {
                                tb_stuk2.stuk_qt -= oldQuantity;
                            }
                            else // في حالة الوحدة القديمة كانت "كبرى"
                            {
                                tb_stuk2.stuk_qt -= oldQuantity * tb_stuk.stuk_qtfacttotal;
                            }
                            db.Entry(tb_stuk2).State = EntityState.Modified;
                            db.SaveChanges();
                        }

                        // حذف السجل من tb_factory
                        db.Entry(tb_factory).State = EntityState.Deleted;
                        db.SaveChanges();

                        toast.txt_caption.Text = "تم الحذف بنجاح";
                        toast.Show();
                        updata_data();
                    }
                    else
                    {
                        dialog.Width = this.Width;
                        dialog.txt_capthion.Text = "لا يوجد تصنيع لحزفها ";
                        dialog.Show();
                    }
                }
            }
            catch
            {
                dialog.Width = this.Width;
                dialog.txt_capthion.Text = "حدث خطأ أثناء الحذف";
                dialog.Show();
            }
        }

        public void updata_data()
        {
            
            db = new DB_storeEntities();
            List<tb_factory> data = db.tb_factory.ToList(); // جلب البيانات
            data.Reverse();
            gridControl1.DataSource = data;
        }

        

        private void btn_search_Click(object sender, EventArgs e)
        {
            var _search = edit_txt.Text;
            List<tb_factory> data = db.tb_factory.Where(x =>  x.cat_name.Contains(_search) || x.cat_name_fact.Contains(_search)).ToList(); // جلب البيانات
            data.Reverse();
            gridControl1.DataSource = data;
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            pl.frm_factory_add frm_supp_Add = new frm_factory_add();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("id"));
             var tb_factory = db.tb_factory.Where(x => x.id == id).FirstOrDefault();
            // frm_supp_Add.edt_name.Text = tb_sell.sell_name;
            // tb_sell = db.tb_sell.Where(x => x.sell_cus == edt_cus.Text).FirstOrDefault();
            // 
            //frm_supp_Add.edt_sell.Text = tb_sell.sell_price.ToString();
            // frm_supp_Add.edt_cat.Text = tb.sell_qt.ToString();
            frm_supp_Add.edt_date.Text = (tb_factory.date).ToString();
            frm_supp_Add.edt_cat.Text = tb_factory.cat_name;
            frm_supp_Add.edt_cat_fact.Text = tb_factory.cat_name_fact;
            frm_supp_Add.edt_qt.Text = tb_factory.qt.ToString();
            frm_supp_Add.edt_cost.Text = tb_factory.cost_all.ToString();
           if(tb_factory.unit=="كبرى")
            {
                frm_supp_Add.big.Checked = true;
            }else
            {
                frm_supp_Add.small.Checked = true;
            }

            frm_supp_Add.edt_cat.Enabled = false;
            frm_supp_Add.edt_cat_fact.Enabled = false;


            // tb_Cus = db.tb_cus.Where(x => x.cus_name == edt_cus.Text).FirstOrDefault();

            frm_supp_Add.id = id;
            frm_supp_Add.btn_add.Text = "حفظ";
            frm_supp_Add.Show();
        }

        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {
            btn_edit_Click(sender, e);
        }
    }
}
