
namespace el_shabander.pl
{
    partial class frm_home
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frm_home));
            DevExpress.XtraEditors.TileItemElement tileItemElement1 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement2 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame1 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement3 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement4 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame2 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement5 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement6 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame3 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement7 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement8 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement9 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement10 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement11 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame4 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement12 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement13 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement14 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame5 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement15 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement16 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement17 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame6 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement18 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement19 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement20 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement21 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement22 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement23 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame7 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement24 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement25 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement26 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame8 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement27 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement28 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement29 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame9 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement30 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement31 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement32 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement33 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame10 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement34 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame11 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement35 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame12 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement36 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement37 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement38 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement39 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame13 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement40 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement41 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement42 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame14 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement43 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement44 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement45 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame15 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement46 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement47 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement48 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement49 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement50 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement51 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame16 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement52 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement53 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement54 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame17 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement55 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement56 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement57 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame18 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement58 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement59 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement60 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement61 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement62 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement63 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame19 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement64 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement65 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement66 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame20 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement67 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement68 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement69 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame21 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement70 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement71 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement72 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement73 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement74 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame22 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement75 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement76 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame23 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement77 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement78 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement79 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement80 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame24 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement81 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement82 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemFrame tileItemFrame25 = new DevExpress.XtraEditors.TileItemFrame();
            DevExpress.XtraEditors.TileItemElement tileItemElement83 = new DevExpress.XtraEditors.TileItemElement();
            DevExpress.XtraEditors.TileItemElement tileItemElement84 = new DevExpress.XtraEditors.TileItemElement();
            this.tileControl1 = new DevExpress.XtraEditors.TileControl();
            this.tileGroup2 = new DevExpress.XtraEditors.TileGroup();
            this.tileItem1 = new DevExpress.XtraEditors.TileItem();
            this.tileItem2 = new DevExpress.XtraEditors.TileItem();
            this.tileItem10 = new DevExpress.XtraEditors.TileItem();
            this.tileItem5 = new DevExpress.XtraEditors.TileItem();
            this.tileItem4 = new DevExpress.XtraEditors.TileItem();
            this.tileItem6 = new DevExpress.XtraEditors.TileItem();
            this.tileItem7 = new DevExpress.XtraEditors.TileItem();
            this.tileItem8 = new DevExpress.XtraEditors.TileItem();
            this.tileItem9 = new DevExpress.XtraEditors.TileItem();
            this.SuspendLayout();
            // 
            // tileControl1
            // 
            this.tileControl1.BackColor = System.Drawing.Color.Transparent;
            this.tileControl1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tileControl1.BackgroundImage")));
            this.tileControl1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.tileControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tileControl1.Groups.Add(this.tileGroup2);
            this.tileControl1.Location = new System.Drawing.Point(0, 0);
            this.tileControl1.MaxId = 17;
            this.tileControl1.Name = "tileControl1";
            this.tileControl1.Size = new System.Drawing.Size(1030, 720);
            this.tileControl1.TabIndex = 4;
            this.tileControl1.Text = "tileControl1";
            // 
            // tileGroup2
            // 
            this.tileGroup2.Items.Add(this.tileItem1);
            this.tileGroup2.Items.Add(this.tileItem2);
            this.tileGroup2.Items.Add(this.tileItem10);
            this.tileGroup2.Items.Add(this.tileItem5);
            this.tileGroup2.Items.Add(this.tileItem4);
            this.tileGroup2.Items.Add(this.tileItem6);
            this.tileGroup2.Items.Add(this.tileItem7);
            this.tileGroup2.Items.Add(this.tileItem8);
            this.tileGroup2.Items.Add(this.tileItem9);
            this.tileGroup2.Name = "tileGroup2";
            // 
            // tileItem1
            // 
            this.tileItem1.AppearanceItem.Normal.BackColor = System.Drawing.Color.Silver;
            this.tileItem1.AppearanceItem.Normal.BackColor2 = System.Drawing.Color.Silver;
            this.tileItem1.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem1.ContentAnimation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            this.tileItem1.CurrentFrameIndex = 1;
            tileItemElement1.AnimateTransition = DevExpress.Utils.DefaultBoolean.True;
            tileItemElement1.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement1.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            tileItemElement1.Appearance.Normal.Options.UseFont = true;
            tileItemElement1.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement1.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image")));
            tileItemElement1.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            tileItemElement1.Text = "الموظفين";
            tileItemElement1.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement2.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement2.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement2.Appearance.Normal.Options.UseFont = true;
            tileItemElement2.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement2.Text = "51";
            tileItemElement2.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            this.tileItem1.Elements.Add(tileItemElement1);
            this.tileItem1.Elements.Add(tileItemElement2);
            this.tileItem1.FrameAnimationInterval = 4000;
            tileItemFrame1.Appearance.BackColor = System.Drawing.Color.Silver;
            tileItemFrame1.Appearance.BackColor2 = System.Drawing.Color.Silver;
            tileItemFrame1.Appearance.Options.UseBackColor = true;
            tileItemElement3.AnimateTransition = DevExpress.Utils.DefaultBoolean.True;
            tileItemElement3.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement3.Appearance.Normal.Options.UseFont = true;
            tileItemElement3.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image1")));
            tileItemElement3.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            tileItemElement3.Text = "الموردين";
            tileItemElement3.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement4.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement4.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement4.Appearance.Normal.Options.UseFont = true;
            tileItemElement4.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement4.Text = "51";
            tileItemElement4.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            tileItemFrame1.Elements.Add(tileItemElement3);
            tileItemFrame1.Elements.Add(tileItemElement4);
            tileItemFrame1.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame1.Image")));
            tileItemFrame2.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemFrame2.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            tileItemFrame2.Appearance.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            tileItemFrame2.Appearance.Options.UseBackColor = true;
            tileItemElement5.AnimateTransition = DevExpress.Utils.DefaultBoolean.True;
            tileItemElement5.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement5.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            tileItemElement5.Appearance.Normal.Options.UseFont = true;
            tileItemElement5.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement5.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image2")));
            tileItemElement5.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            tileItemElement5.Text = "الموظفين";
            tileItemElement5.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement6.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement6.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement6.Appearance.Normal.Options.UseFont = true;
            tileItemElement6.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement6.Text = "51";
            tileItemElement6.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            tileItemFrame2.Elements.Add(tileItemElement5);
            tileItemFrame2.Elements.Add(tileItemElement6);
            tileItemFrame2.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame2.Image")));
            tileItemFrame3.Appearance.BackColor = System.Drawing.Color.YellowGreen;
            tileItemFrame3.Appearance.BackColor2 = System.Drawing.Color.YellowGreen;
            tileItemFrame3.Appearance.Options.UseBackColor = true;
            tileItemElement7.AnimateTransition = DevExpress.Utils.DefaultBoolean.True;
            tileItemElement7.Appearance.Normal.BackColor = System.Drawing.Color.Transparent;
            tileItemElement7.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement7.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement7.Appearance.Normal.Options.UseFont = true;
            tileItemElement7.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image3")));
            tileItemElement7.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            tileItemElement7.Text = "العملاء";
            tileItemElement7.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement8.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement8.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement8.Appearance.Normal.Options.UseFont = true;
            tileItemElement8.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement8.Text = "51";
            tileItemElement8.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomLeft;
            tileItemFrame3.Elements.Add(tileItemElement7);
            tileItemFrame3.Elements.Add(tileItemElement8);
            tileItemFrame3.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame3.Image")));
            this.tileItem1.Frames.Add(tileItemFrame1);
            this.tileItem1.Frames.Add(tileItemFrame2);
            this.tileItem1.Frames.Add(tileItemFrame3);
            this.tileItem1.Id = 2;
            this.tileItem1.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem1.Name = "tileItem1";
            this.tileItem1.ItemDoubleClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem1_ItemClick);
            // 
            // tileItem2
            // 
            this.tileItem2.AppearanceItem.Normal.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            this.tileItem2.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem2.CurrentFrameIndex = 2;
            tileItemElement9.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement9.Appearance.Normal.ForeColor = System.Drawing.Color.White;
            tileItemElement9.Appearance.Normal.Options.UseFont = true;
            tileItemElement9.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement9.Text = "الاصناف";
            tileItemElement9.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement10.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image4")));
            tileItemElement10.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement10.ImageOptions.ImageBorderColor = System.Drawing.Color.White;
            tileItemElement10.Text = "";
            tileItemElement11.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement11.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement11.Appearance.Normal.Options.UseFont = true;
            tileItemElement11.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement11.Text = "15";
            tileItemElement11.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            this.tileItem2.Elements.Add(tileItemElement9);
            this.tileItem2.Elements.Add(tileItemElement10);
            this.tileItem2.Elements.Add(tileItemElement11);
            this.tileItem2.FrameAnimationInterval = 4000;
            tileItemFrame4.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollRight;
            tileItemFrame4.Appearance.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            tileItemFrame4.Appearance.Options.UseBackColor = true;
            tileItemElement12.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement12.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            tileItemElement12.Appearance.Normal.Options.UseFont = true;
            tileItemElement12.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement12.Text = "المشتريات";
            tileItemElement12.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement13.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image5")));
            tileItemElement13.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement13.ImageOptions.ImageBorderColor = System.Drawing.Color.White;
            tileItemElement13.Text = "";
            tileItemElement14.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement14.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement14.Appearance.Normal.Options.UseFont = true;
            tileItemElement14.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement14.Text = "15";
            tileItemElement14.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemFrame4.Elements.Add(tileItemElement12);
            tileItemFrame4.Elements.Add(tileItemElement13);
            tileItemFrame4.Elements.Add(tileItemElement14);
            tileItemFrame5.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.SegmentedFade;
            tileItemFrame5.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            tileItemFrame5.Appearance.Options.UseBackColor = true;
            tileItemElement15.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement15.Appearance.Normal.ForeColor = System.Drawing.Color.DarkOliveGreen;
            tileItemElement15.Appearance.Normal.Options.UseFont = true;
            tileItemElement15.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement15.Text = "المبيعات";
            tileItemElement15.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement16.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image6")));
            tileItemElement16.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement16.ImageOptions.ImageBorderColor = System.Drawing.Color.White;
            tileItemElement16.Text = "";
            tileItemElement17.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement17.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement17.Appearance.Normal.Options.UseFont = true;
            tileItemElement17.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement17.Text = "15";
            tileItemElement17.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemFrame5.Elements.Add(tileItemElement15);
            tileItemFrame5.Elements.Add(tileItemElement16);
            tileItemFrame5.Elements.Add(tileItemElement17);
            tileItemFrame6.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemFrame6.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            tileItemFrame6.Appearance.Options.UseBackColor = true;
            tileItemElement18.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement18.Appearance.Normal.ForeColor = System.Drawing.Color.White;
            tileItemElement18.Appearance.Normal.Options.UseFont = true;
            tileItemElement18.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement18.Text = "الاصناف";
            tileItemElement18.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement19.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image7")));
            tileItemElement19.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement19.ImageOptions.ImageBorderColor = System.Drawing.Color.White;
            tileItemElement19.Text = "";
            tileItemElement20.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement20.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement20.Appearance.Normal.Options.UseFont = true;
            tileItemElement20.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement20.Text = "15";
            tileItemElement20.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemFrame6.Elements.Add(tileItemElement18);
            tileItemFrame6.Elements.Add(tileItemElement19);
            tileItemFrame6.Elements.Add(tileItemElement20);
            this.tileItem2.Frames.Add(tileItemFrame4);
            this.tileItem2.Frames.Add(tileItemFrame5);
            this.tileItem2.Frames.Add(tileItemFrame6);
            this.tileItem2.Id = 3;
            this.tileItem2.ItemSize = DevExpress.XtraEditors.TileItemSize.Large;
            this.tileItem2.Name = "tileItem2";
            this.tileItem2.ItemDoubleClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem2_ItemClick);
            // 
            // tileItem10
            // 
            this.tileItem10.AppearanceItem.Normal.BackColor = System.Drawing.Color.YellowGreen;
            this.tileItem10.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement21.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image8")));
            tileItemElement21.Text = "";
            tileItemElement22.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement22.Appearance.Normal.Options.UseFont = true;
            tileItemElement22.Text = "العملاء";
            tileItemElement22.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement23.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement23.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement23.Appearance.Normal.Options.UseFont = true;
            tileItemElement23.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement23.Text = "15";
            tileItemElement23.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            this.tileItem10.Elements.Add(tileItemElement21);
            this.tileItem10.Elements.Add(tileItemElement22);
            this.tileItem10.Elements.Add(tileItemElement23);
            this.tileItem10.FrameAnimationInterval = 9000;
            tileItemFrame7.Appearance.BackColor = System.Drawing.Color.YellowGreen;
            tileItemFrame7.Appearance.BackColor2 = System.Drawing.Color.YellowGreen;
            tileItemFrame7.Appearance.Options.UseBackColor = true;
            tileItemElement24.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image9")));
            tileItemElement24.Text = "";
            tileItemElement25.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement25.Appearance.Normal.Options.UseFont = true;
            tileItemElement25.Text = "العملاء";
            tileItemElement25.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement26.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement26.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement26.Appearance.Normal.Options.UseFont = true;
            tileItemElement26.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement26.Text = "15";
            tileItemElement26.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            tileItemFrame7.Elements.Add(tileItemElement24);
            tileItemFrame7.Elements.Add(tileItemElement25);
            tileItemFrame7.Elements.Add(tileItemElement26);
            tileItemFrame7.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame7.Image")));
            tileItemFrame8.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemFrame8.Appearance.BackColor = System.Drawing.Color.Silver;
            tileItemFrame8.Appearance.BackColor2 = System.Drawing.Color.Silver;
            tileItemFrame8.Appearance.Options.UseBackColor = true;
            tileItemElement27.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image10")));
            tileItemElement27.Text = "";
            tileItemElement28.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement28.Appearance.Normal.Options.UseFont = true;
            tileItemElement28.Text = "الموردين";
            tileItemElement28.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement29.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement29.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement29.Appearance.Normal.Options.UseFont = true;
            tileItemElement29.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement29.Text = "15";
            tileItemElement29.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            tileItemFrame8.Elements.Add(tileItemElement27);
            tileItemFrame8.Elements.Add(tileItemElement28);
            tileItemFrame8.Elements.Add(tileItemElement29);
            tileItemFrame8.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame8.Image")));
            tileItemFrame9.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            tileItemFrame9.Appearance.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            tileItemFrame9.Appearance.Options.UseBackColor = true;
            tileItemElement30.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image11")));
            tileItemElement30.Text = "";
            tileItemElement31.Appearance.Normal.BackColor = System.Drawing.Color.Transparent;
            tileItemElement31.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement31.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            tileItemElement31.Appearance.Normal.Options.UseBackColor = true;
            tileItemElement31.Appearance.Normal.Options.UseFont = true;
            tileItemElement31.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement31.Text = "الموظفين";
            tileItemElement31.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement32.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement32.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement32.Appearance.Normal.Options.UseFont = true;
            tileItemElement32.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement32.Text = "15";
            tileItemElement32.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            tileItemFrame9.Elements.Add(tileItemElement30);
            tileItemFrame9.Elements.Add(tileItemElement31);
            tileItemFrame9.Elements.Add(tileItemElement32);
            tileItemFrame9.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame9.Image")));
            this.tileItem10.Frames.Add(tileItemFrame7);
            this.tileItem10.Frames.Add(tileItemFrame8);
            this.tileItem10.Frames.Add(tileItemFrame9);
            this.tileItem10.Id = 16;
            this.tileItem10.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem10.Name = "tileItem10";
            this.tileItem10.ItemDoubleClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem10_ItemClick);
            // 
            // tileItem5
            // 
            this.tileItem5.BackgroundImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            this.tileItem5.BackgroundImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.Stretch;
            this.tileItem5.CurrentFrameIndex = 2;
            tileItemElement33.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image12")));
            tileItemElement33.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement33.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement33.Text = "";
            tileItemElement33.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            this.tileItem5.Elements.Add(tileItemElement33);
            this.tileItem5.FrameAnimationInterval = 5000;
            tileItemFrame10.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemFrame10.Appearance.BackColor = System.Drawing.Color.White;
            tileItemFrame10.Appearance.Options.UseBackColor = true;
            tileItemElement34.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image13")));
            tileItemElement34.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement34.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement34.Text = "";
            tileItemFrame10.Elements.Add(tileItemElement34);
            tileItemFrame10.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame10.Image")));
            tileItemFrame11.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemFrame11.Appearance.BackColor = System.Drawing.Color.White;
            tileItemFrame11.Appearance.Options.UseBackColor = true;
            tileItemElement35.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image14")));
            tileItemElement35.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement35.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement35.Text = "";
            tileItemFrame11.Elements.Add(tileItemElement35);
            tileItemFrame11.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame11.Image")));
            tileItemFrame12.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemFrame12.Appearance.BackColor = System.Drawing.Color.White;
            tileItemFrame12.Appearance.Options.UseBackColor = true;
            tileItemElement36.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image15")));
            tileItemElement36.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement36.ImageOptions.ImageScaleMode = DevExpress.XtraEditors.TileItemImageScaleMode.ZoomInside;
            tileItemElement36.Text = "";
            tileItemElement36.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemFrame12.Elements.Add(tileItemElement36);
            tileItemFrame12.Image = ((System.Drawing.Image)(resources.GetObject("tileItemFrame12.Image")));
            this.tileItem5.Frames.Add(tileItemFrame10);
            this.tileItem5.Frames.Add(tileItemFrame11);
            this.tileItem5.Frames.Add(tileItemFrame12);
            this.tileItem5.Id = 8;
            this.tileItem5.ItemSize = DevExpress.XtraEditors.TileItemSize.Large;
            this.tileItem5.Name = "tileItem5";
            // 
            // tileItem4
            // 
            this.tileItem4.AppearanceItem.Normal.BackColor = System.Drawing.Color.SandyBrown;
            this.tileItem4.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement37.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement37.Appearance.Normal.Options.UseFont = true;
            tileItemElement37.Text = "الاصناف";
            tileItemElement37.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement38.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image16")));
            tileItemElement38.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement38.Text = "";
            tileItemElement38.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement39.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement39.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement39.Appearance.Normal.Options.UseFont = true;
            tileItemElement39.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement39.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemElement39.Text = "15";
            tileItemElement39.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            this.tileItem4.Elements.Add(tileItemElement37);
            this.tileItem4.Elements.Add(tileItemElement38);
            this.tileItem4.Elements.Add(tileItemElement39);
            this.tileItem4.FrameAnimationInterval = 10000;
            tileItemFrame13.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            tileItemFrame13.Appearance.Options.UseBackColor = true;
            tileItemElement40.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement40.Appearance.Normal.Options.UseFont = true;
            tileItemElement40.Text = "الاصناف";
            tileItemElement40.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement41.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image17")));
            tileItemElement41.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement41.Text = "";
            tileItemElement41.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement42.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement42.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement42.Appearance.Normal.Options.UseFont = true;
            tileItemElement42.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement42.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemElement42.Text = "15";
            tileItemElement42.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemFrame13.Elements.Add(tileItemElement40);
            tileItemFrame13.Elements.Add(tileItemElement41);
            tileItemFrame13.Elements.Add(tileItemElement42);
            tileItemFrame14.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.SegmentedFade;
            tileItemFrame14.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            tileItemFrame14.Appearance.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            tileItemFrame14.Appearance.Options.UseBackColor = true;
            tileItemElement43.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement43.Appearance.Normal.ForeColor = System.Drawing.Color.DarkOliveGreen;
            tileItemElement43.Appearance.Normal.Options.UseFont = true;
            tileItemElement43.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement43.Text = "المبيعات";
            tileItemElement43.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement44.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image18")));
            tileItemElement44.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement44.Text = "";
            tileItemElement44.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement45.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement45.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement45.Appearance.Normal.Options.UseFont = true;
            tileItemElement45.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement45.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemElement45.Text = "15";
            tileItemElement45.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemFrame14.Elements.Add(tileItemElement43);
            tileItemFrame14.Elements.Add(tileItemElement44);
            tileItemFrame14.Elements.Add(tileItemElement45);
            tileItemFrame15.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemFrame15.Appearance.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            tileItemFrame15.Appearance.Options.UseBackColor = true;
            tileItemElement46.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement46.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            tileItemElement46.Appearance.Normal.Options.UseFont = true;
            tileItemElement46.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement46.Text = "المشتريات";
            tileItemElement46.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement47.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image19")));
            tileItemElement47.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement47.Text = "";
            tileItemElement47.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement48.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement48.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement48.Appearance.Normal.Options.UseFont = true;
            tileItemElement48.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement48.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemElement48.Text = "15";
            tileItemElement48.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemFrame15.Elements.Add(tileItemElement46);
            tileItemFrame15.Elements.Add(tileItemElement47);
            tileItemFrame15.Elements.Add(tileItemElement48);
            this.tileItem4.Frames.Add(tileItemFrame13);
            this.tileItem4.Frames.Add(tileItemFrame14);
            this.tileItem4.Frames.Add(tileItemFrame15);
            this.tileItem4.Id = 5;
            this.tileItem4.ItemSize = DevExpress.XtraEditors.TileItemSize.Large;
            this.tileItem4.Name = "tileItem4";
            this.tileItem4.ItemDoubleClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem4_ItemClick);
            // 
            // tileItem6
            // 
            this.tileItem6.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.tileItem6.AppearanceItem.Normal.Options.UseBackColor = true;
            tileItemElement49.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement49.Appearance.Normal.ForeColor = System.Drawing.Color.DarkOliveGreen;
            tileItemElement49.Appearance.Normal.Options.UseFont = true;
            tileItemElement49.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement49.Text = "المبيعات";
            tileItemElement49.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement50.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image20")));
            tileItemElement50.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement50.Text = "";
            tileItemElement50.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement51.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement51.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement51.Appearance.Normal.Options.UseFont = true;
            tileItemElement51.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement51.Text = "145";
            tileItemElement51.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            this.tileItem6.Elements.Add(tileItemElement49);
            this.tileItem6.Elements.Add(tileItemElement50);
            this.tileItem6.Elements.Add(tileItemElement51);
            tileItemFrame16.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            tileItemFrame16.Appearance.Options.UseBackColor = true;
            tileItemElement52.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement52.Appearance.Normal.ForeColor = System.Drawing.Color.DarkOliveGreen;
            tileItemElement52.Appearance.Normal.Options.UseFont = true;
            tileItemElement52.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement52.Text = "المبيعات";
            tileItemElement52.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement53.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image21")));
            tileItemElement53.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement53.Text = "";
            tileItemElement53.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement54.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement54.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement54.Appearance.Normal.Options.UseFont = true;
            tileItemElement54.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement54.Text = "145";
            tileItemElement54.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemFrame16.Elements.Add(tileItemElement52);
            tileItemFrame16.Elements.Add(tileItemElement53);
            tileItemFrame16.Elements.Add(tileItemElement54);
            tileItemFrame17.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.SegmentedFade;
            tileItemFrame17.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            tileItemFrame17.Appearance.Options.UseBackColor = true;
            tileItemElement55.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement55.Appearance.Normal.ForeColor = System.Drawing.Color.White;
            tileItemElement55.Appearance.Normal.Options.UseFont = true;
            tileItemElement55.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement55.Text = "الاصناف";
            tileItemElement55.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement56.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image22")));
            tileItemElement56.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement56.Text = "";
            tileItemElement56.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement57.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement57.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement57.Appearance.Normal.Options.UseFont = true;
            tileItemElement57.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement57.Text = "145";
            tileItemElement57.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemFrame17.Elements.Add(tileItemElement55);
            tileItemFrame17.Elements.Add(tileItemElement56);
            tileItemFrame17.Elements.Add(tileItemElement57);
            tileItemFrame18.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemFrame18.Appearance.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            tileItemFrame18.Appearance.BackColor2 = System.Drawing.SystemColors.ButtonHighlight;
            tileItemFrame18.Appearance.Options.UseBackColor = true;
            tileItemElement58.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement58.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            tileItemElement58.Appearance.Normal.Options.UseFont = true;
            tileItemElement58.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement58.Text = "المشتريات";
            tileItemElement58.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement59.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image23")));
            tileItemElement59.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement59.Text = "";
            tileItemElement59.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement60.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement60.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement60.Appearance.Normal.Options.UseFont = true;
            tileItemElement60.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement60.Text = "145";
            tileItemElement60.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemFrame18.Elements.Add(tileItemElement58);
            tileItemFrame18.Elements.Add(tileItemElement59);
            tileItemFrame18.Elements.Add(tileItemElement60);
            this.tileItem6.Frames.Add(tileItemFrame16);
            this.tileItem6.Frames.Add(tileItemFrame17);
            this.tileItem6.Frames.Add(tileItemFrame18);
            this.tileItem6.Id = 9;
            this.tileItem6.ItemSize = DevExpress.XtraEditors.TileItemSize.Large;
            this.tileItem6.Name = "tileItem6";
            this.tileItem6.ItemDoubleClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem6_ItemClick);
            // 
            // tileItem7
            // 
            this.tileItem7.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.tileItem7.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem7.CurrentFrameIndex = 2;
            tileItemElement61.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement61.Appearance.Normal.ForeColor = System.Drawing.Color.White;
            tileItemElement61.Appearance.Normal.Options.UseFont = true;
            tileItemElement61.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement61.Text = "العملاء";
            tileItemElement61.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement62.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image24")));
            tileItemElement62.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            tileItemElement62.Text = "";
            tileItemElement62.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement63.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement63.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement63.Appearance.Normal.Options.UseFont = true;
            tileItemElement63.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement63.Text = "20";
            this.tileItem7.Elements.Add(tileItemElement61);
            this.tileItem7.Elements.Add(tileItemElement62);
            this.tileItem7.Elements.Add(tileItemElement63);
            this.tileItem7.FrameAnimationInterval = 6000;
            tileItemFrame19.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            tileItemFrame19.Appearance.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            tileItemFrame19.Appearance.Options.UseBackColor = true;
            tileItemElement64.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement64.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            tileItemElement64.Appearance.Normal.Options.UseFont = true;
            tileItemElement64.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement64.Text = "الموظفين";
            tileItemElement64.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement65.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image25")));
            tileItemElement65.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            tileItemElement65.Text = "";
            tileItemElement65.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement66.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement66.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement66.Appearance.Normal.Options.UseFont = true;
            tileItemElement66.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement66.Text = "20";
            tileItemFrame19.Elements.Add(tileItemElement64);
            tileItemFrame19.Elements.Add(tileItemElement65);
            tileItemFrame19.Elements.Add(tileItemElement66);
            tileItemFrame20.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.RandomSegmentedFade;
            tileItemFrame20.Appearance.BackColor = System.Drawing.Color.Silver;
            tileItemFrame20.Appearance.BackColor2 = System.Drawing.Color.Silver;
            tileItemFrame20.Appearance.Options.UseBackColor = true;
            tileItemElement67.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement67.Appearance.Normal.ForeColor = System.Drawing.Color.White;
            tileItemElement67.Appearance.Normal.Options.UseFont = true;
            tileItemElement67.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement67.Text = "الموردين";
            tileItemElement67.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement68.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image26")));
            tileItemElement68.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            tileItemElement68.Text = "";
            tileItemElement68.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement69.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement69.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement69.Appearance.Normal.Options.UseFont = true;
            tileItemElement69.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement69.Text = "20";
            tileItemFrame20.Elements.Add(tileItemElement67);
            tileItemFrame20.Elements.Add(tileItemElement68);
            tileItemFrame20.Elements.Add(tileItemElement69);
            tileItemFrame21.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollLeft;
            tileItemFrame21.Appearance.BackColor = System.Drawing.Color.YellowGreen;
            tileItemFrame21.Appearance.BackColor2 = System.Drawing.Color.YellowGreen;
            tileItemFrame21.Appearance.Options.UseBackColor = true;
            tileItemElement70.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement70.Appearance.Normal.ForeColor = System.Drawing.Color.White;
            tileItemElement70.Appearance.Normal.Options.UseFont = true;
            tileItemElement70.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement70.Text = "العملاء";
            tileItemElement70.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement71.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image27")));
            tileItemElement71.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomRight;
            tileItemElement71.Text = "";
            tileItemElement71.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.MiddleCenter;
            tileItemElement72.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement72.Appearance.Normal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            tileItemElement72.Appearance.Normal.Options.UseFont = true;
            tileItemElement72.Appearance.Normal.Options.UseForeColor = true;
            tileItemElement72.Text = "20";
            tileItemFrame21.Elements.Add(tileItemElement70);
            tileItemFrame21.Elements.Add(tileItemElement71);
            tileItemFrame21.Elements.Add(tileItemElement72);
            this.tileItem7.Frames.Add(tileItemFrame19);
            this.tileItem7.Frames.Add(tileItemFrame20);
            this.tileItem7.Frames.Add(tileItemFrame21);
            this.tileItem7.Id = 10;
            this.tileItem7.ItemSize = DevExpress.XtraEditors.TileItemSize.Wide;
            this.tileItem7.Name = "tileItem7";
            this.tileItem7.ItemDoubleClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem7_ItemClick);
            // 
            // tileItem8
            // 
            this.tileItem8.AppearanceItem.Normal.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.tileItem8.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem8.CurrentFrameIndex = 1;
            tileItemElement73.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement73.Appearance.Normal.Options.UseFont = true;
            tileItemElement73.Text = "المصاريف";
            tileItemElement73.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement74.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image28")));
            tileItemElement74.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemElement74.Text = "";
            tileItemElement74.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            this.tileItem8.Elements.Add(tileItemElement73);
            this.tileItem8.Elements.Add(tileItemElement74);
            this.tileItem8.FrameAnimationInterval = 5000;
            tileItemFrame22.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollDown;
            tileItemFrame22.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            tileItemFrame22.Appearance.Options.UseBackColor = true;
            tileItemElement75.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement75.Appearance.Normal.Options.UseFont = true;
            tileItemElement75.Text = "التقارير";
            tileItemElement75.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement76.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image29")));
            tileItemElement76.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemElement76.Text = "";
            tileItemFrame22.Elements.Add(tileItemElement75);
            tileItemFrame22.Elements.Add(tileItemElement76);
            tileItemFrame23.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemFrame23.Appearance.BackColor = System.Drawing.Color.LightCoral;
            tileItemFrame23.Appearance.Options.UseBackColor = true;
            tileItemElement77.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement77.Appearance.Normal.Options.UseFont = true;
            tileItemElement77.Text = "المصاريف";
            tileItemElement77.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement78.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image30")));
            tileItemElement78.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemElement78.Text = "";
            tileItemElement78.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemFrame23.Elements.Add(tileItemElement77);
            tileItemFrame23.Elements.Add(tileItemElement78);
            this.tileItem8.Frames.Add(tileItemFrame22);
            this.tileItem8.Frames.Add(tileItemFrame23);
            this.tileItem8.Id = 11;
            this.tileItem8.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem8.Name = "tileItem8";
            this.tileItem8.ItemDoubleClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem8_ItemClick);
            // 
            // tileItem9
            // 
            this.tileItem9.AppearanceItem.Normal.BackColor = System.Drawing.Color.LightCoral;
            this.tileItem9.AppearanceItem.Normal.Options.UseBackColor = true;
            this.tileItem9.CurrentFrameIndex = 1;
            tileItemElement79.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement79.Appearance.Normal.Options.UseFont = true;
            tileItemElement79.Text = "التقارير";
            tileItemElement79.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement80.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image31")));
            tileItemElement80.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemElement80.Text = "";
            this.tileItem9.Elements.Add(tileItemElement79);
            this.tileItem9.Elements.Add(tileItemElement80);
            this.tileItem9.FrameAnimationInterval = 5000;
            tileItemFrame24.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollLeft;
            tileItemFrame24.Appearance.BackColor = System.Drawing.Color.LightCoral;
            tileItemFrame24.Appearance.Options.UseBackColor = true;
            tileItemElement81.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement81.Appearance.Normal.Options.UseFont = true;
            tileItemElement81.Text = "المصاريف";
            tileItemElement81.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement82.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image32")));
            tileItemElement82.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemElement82.Text = "";
            tileItemFrame24.Elements.Add(tileItemElement81);
            tileItemFrame24.Elements.Add(tileItemElement82);
            tileItemFrame25.Animation = DevExpress.XtraEditors.TileItemContentAnimationType.ScrollTop;
            tileItemFrame25.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            tileItemFrame25.Appearance.Options.UseBackColor = true;
            tileItemElement83.Appearance.Normal.Font = new System.Drawing.Font("Cairo", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            tileItemElement83.Appearance.Normal.Options.UseFont = true;
            tileItemElement83.Text = "التقارير";
            tileItemElement83.TextAlignment = DevExpress.XtraEditors.TileItemContentAlignment.TopCenter;
            tileItemElement84.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("resource.Image33")));
            tileItemElement84.ImageOptions.ImageAlignment = DevExpress.XtraEditors.TileItemContentAlignment.BottomCenter;
            tileItemElement84.Text = "";
            tileItemFrame25.Elements.Add(tileItemElement83);
            tileItemFrame25.Elements.Add(tileItemElement84);
            this.tileItem9.Frames.Add(tileItemFrame24);
            this.tileItem9.Frames.Add(tileItemFrame25);
            this.tileItem9.Id = 12;
            this.tileItem9.ItemSize = DevExpress.XtraEditors.TileItemSize.Medium;
            this.tileItem9.Name = "tileItem9";
            this.tileItem9.ItemDoubleClick += new DevExpress.XtraEditors.TileItemClickEventHandler(this.tileItem9_ItemClick);
            // 
            // frm_home
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            this.ClientSize = new System.Drawing.Size(1030, 720);
            this.Controls.Add(this.tileControl1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frm_home";
            this.Text = "frm_home";
            this.Activated += new System.EventHandler(this.frm_home_Activated);
            this.TextChanged += new System.EventHandler(this.frm_home_TextChanged);
            this.ResumeLayout(false);

        }

        #endregion

        public DevExpress.XtraEditors.TileControl tileControl1;
        private DevExpress.XtraEditors.TileGroup tileGroup2;
        public DevExpress.XtraEditors.TileItem tileItem1;
        public DevExpress.XtraEditors.TileItem tileItem2;
        public DevExpress.XtraEditors.TileItem tileItem10;
        public DevExpress.XtraEditors.TileItem tileItem5;
        public DevExpress.XtraEditors.TileItem tileItem4;
        public DevExpress.XtraEditors.TileItem tileItem6;
        public DevExpress.XtraEditors.TileItem tileItem7;
        public DevExpress.XtraEditors.TileItem tileItem8;
        public DevExpress.XtraEditors.TileItem tileItem9;
    }
}