using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;


using el_shabander.epl;
namespace el_shabander.epl
{
   
    public partial class notifaction : Form
    {
        gold_shopEntities db = new gold_shopEntities();
        Notfication notfication = new Notfication();
        public notifaction()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            el_shabander.gold_shopEntities dbContext = new el_shabander.gold_shopEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Notfications.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.Notfications.Local.ToBindingList().Reverse();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }


        public void updata_data()
        {

           
            List<Notfication> data = db.Notfications.ToList(); // جلب البيانات
            data.Reverse();
            gridControl1.DataSource = data;
        }
        private void txt_capthion_Click(object sender, EventArgs e)
        {
            this.Close();
        }
        int id;
        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {

            id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("id"));
            notfication = db.Notfications.Where(x => x.id == id).FirstOrDefault();
            pl.frm_notification_view frm = new pl.frm_notification_view(notfication.notfication1);
            this.Close();
            frm.Show();
        }
    }
}
